### ISSUE TITLE
Lemmy detected, but rendered link is invalid.

### ISSUE THREAD

**Issue by Sakrecoer** [stefanbohacek/fediverse-share-button#11]
Inputting a lemmy instance to the fedi-share button makes it display the lemmy logo. But when pressed the button takes the person to a landing-page to create a post that Lemmy does not recognize. 

Happens with Lemmy BE: 0.19.5

This is the output:

`https://domain.tld/share?text=Fediverse%20sharing%20button%20%7C%20Stefan%20Bohacek%0A%0Ahttps%3A%2F%2Fstefanbohacek.com%2Fproject%2Ffediverse-sharing-button%2F`

Unfortunately, I haven't been able to locate a way to produce a link that lemmy can parse.

**Comment by Sakrecoer** [comment]
This format seems to work:

`https://lemmy.domain.tld/create_post?title=A%20Title&url=https://test.domain.tld&body=Some%20text%20here`

**Comment by stefanbohacek** [comment]
@Sakrecoer  Thank you for opening this issue and a PR for this!

I tried this on lemmy.world (via https://lemmy.world/create_post?title=A%20Title&url=https://test.domain.tld&body=Some%20text%20here) and it looks like this is no longer working?

I do see the issue reported and fixed in https://github.com/LemmyNet/lemmy-ui/issues/1913, but perhaps this particular instance is running an older version? Not too sure how to confirm that.

**Comment by Sakrecoer** [comment]
Strange... However, the link you pasted is not what the demo page is rendering. It renders a `domain.tld/share?text=...`

see: https://stefanbohacek.com/project/fediverse-sharing-button/

**Comment by stefanbohacek** [comment]
Yes, I just checked this, thank you! I will merge this PR and add a note about some Lemmy instances having this issue. Thank you so much!

**Comment by Sakrecoer** [comment]
`lemmy.world` is running 0.19.3 and i tried on 0.19.5 where it worked.

**Comment by stefanbohacek** [comment]
Thank you for checking that! And yes, this should still be fixed in the widget, as the URL is incorrect. I will go ahead and merge your PR and add a note about the issue on older Lemmy instances.

Thank you so much for your help!
